### ISSUE TITLE
Failing with no message on nx workspace

### ISSUE THREAD

**Issue by DaSchTour** [kyubisation/angular-t9n#9] opened 2021-12-21 15:56 UTC
I tried to run this inside an nx workspace, but sadly it fails without any error message. Even in debug mode it fails without any messages. Could you add a little bit of logging so it would be possible to debug errors.

**Comment by kyubisation** [comment] 2021-12-21 16:06
Sure. Could you provide a minimal reproduction? I'm not directly familiar with nx workspaces.

**Comment by kyubisation** [comment] 2022-06-05 14:16
Closing due to lack of reaction. Added additional log statements.

**Closed by kyubisation** 2022-06-05 14:16 UTC
